name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      buildDir: '${{ github.workspace }}/build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
